name       : doublecmd
version    : 0.9.8
release    : 7
source     :
    - http://sourceforge.net/projects/doublecmd/files/Double%20Commander%20Source/doublecmd-0.9.8-src.tar.gz/download : d26ec329fa80e67b100d60413477cf3d63dcd72bcc0f1c672e84a231ce47dda6
homepage   : https://doublecmd.sourceforge.io/
license    : GPL-2.0-or-later
component  : desktop
summary    : Twin-panel (commander-style) file manager
description: |
    Double Commander is a cross platform open source file manager with two panels side by side. It is inspired by Total Commander and features some new ideas.
builddeps  :
    - pkgconfig(gtk+-2.0)
    - lazarus
setup      : |
    sed -e 's|\$(which lazbuild)|"\$(which lazbuild) --lazarusdir=/usr/share/lazarus"|' -i build.sh
build      : |
    ./build.sh beta gtk2
install    : |
    ./install/linux/install.sh --install-prefix="$installdir"
