name       : doublecmd
version    : 0.9.7
release    : 6
source     :
    - http://sourceforge.net/projects/doublecmd/files/Double%20Commander%20Source/doublecmd-0.9.7-src.tar.gz/download : 390e5f88dac0947d3193802248cfdbc5684403b67ff8a798958bdc27d1fcf07a
homepage   : https://doublecmd.sourceforge.io/
license    : GPL-2.0-or-later
component  : desktop
summary    : Twin-panel (commander-style) file manager
description: |
    Double Commander is a cross platform open source file manager with two panels side by side. It is inspired by Total Commander and features some new ideas.
builddeps  :
    - pkgconfig(gtk+-2.0)
    - lazarus
setup      : |
    sed -e 's|\$(which lazbuild)|"\$(which lazbuild) --lazarusdir=/usr/share/lazarus"|' -i build.sh
build      : |
    ./build.sh beta gtk2
install    : |
    ./install/linux/install.sh --install-prefix="$installdir"
