name       : doublecmd
version    : 0.9.6
release    : 5
source     :
    - http://sourceforge.net/projects/doublecmd/files/Double%20Commander%20Source/doublecmd-0.9.6-src.tar.gz/download : 43af2b214b9c5115ed6ba436ecfc1e26222bc2b61217cb8cae67e979c3aeb5dc
license    : GPL-2.0-or-later
component  : desktop
summary    : Twin-panel (commander-style) file manager
description: |
    Double Commander is a cross platform open source file manager with two panels side by side. It is inspired by Total Commander and features some new ideas.
builddeps  :
    - pkgconfig(gtk+-2.0)
    - lazarus
setup      : |
    sed -e 's|\$(which lazbuild)|"\$(which lazbuild) --lazarusdir=/usr/share/lazarus"|' -i build.sh
build      : |
    ./build.sh beta gtk2
install    : |
    ./install/linux/install.sh --install-prefix="$installdir"
