name       : doublecmd
version    : 0.9.2
release    : 3
source     :
    - https://netix.dl.sourceforge.net/project/doublecmd/Double%20Commander%20Source/doublecmd-0.9.2-src.tar.gz : a0c27ae8ee4890676a47c2ce5e0cc87684a3bec43c1f281d750c531b9560679a
license    : GPL-2.0-or-later
component  : desktop
summary    : Twin-panel (commander-style) file manager
description: |
    Double Commander is a cross platform open source file manager with two panels side by side. It is inspired by Total Commander and features some new ideas.
builddeps  :
    - pkgconfig(gtk+-2.0)
    - lazarus
setup      : |
    sed -e 's|\$(which lazbuild)|"\$(which lazbuild) --lazarusdir=/usr/share/lazarus"|' -i build.sh
build      : |
    ./build.sh beta gtk2
install    : |
    ./install/linux/install.sh --install-prefix="$installdir"
