name       : doublecmd
version    : 1.0.9
release    : 18
source     :
    - http://sourceforge.net/projects/doublecmd/files/Double%20Commander%20Source/doublecmd-1.0.9-src.tar.gz/download : 8754cfbd2a5de1929d08ede24e7cec152eb9707c3745de17acb71e55e15c7abb
homepage   : https://doublecmd.sourceforge.io/
license    : GPL-2.0-or-later
component  :
    - desktop
    - ^doublecmd-qt : desktop
summary    :
    - Twin-panel (commander-style) file manager (GTK)
    - ^doublecmd-qt : Twin-panel (commander-style) file manager (Qt5)
description:
    - Double Commander GTK is a cross platform open source file manager with two panels side by side. It is inspired by Total Commander and features some new ideas.
    - ^doublecmd-qt : Double Commander QT5 is a cross platform open source file manager with two panels side by side. It is inspired by Total Commander and features some new ideas.
patterns   :
    - ^doublecmd-qt :
        - /usr/*/*doublecmd-qt*
        - /usr/share/*/*doublecmd-qt*
        - /usr/share/*/*/*doublecmd-qt*
        - /usr/share/icons/hicolor/scalable/apps/doublecmd-qt.svg
builddeps  :
    - pkgconfig(gtk+-2.0)
    - lazarus
    - qt5pas-devel
setup      : |
    sed -e 's|\$(which lazbuild)|"\$(which lazbuild) --lazarusdir=/usr/share/lazarus"|' -i build.sh
    cp -r ../doublecmd-${version} ../doublecmd-qt-${version}
    cd ../doublecmd-qt-${version}
    sed -i -e "s|doublecmd|doublecmd-qt|g" install/linux/install.sh install/linux/doublecmd.desktop
    mv install/linux/doublecmd.desktop install/linux/doublecmd-qt.desktop
    mv install/linux/org.doublecmd.root.policy install/linux/org.doublecmd-qt.root.policy
    mv install/linux/doublecmd.1 install/linux/doublecmd-qt.1
    mv pixmaps/mainicon/alt/doublecmd.svg pixmaps/mainicon/alt/doublecmd-qt.svg
    mv doublecmd.help doublecmd-qt.help
    mv doublecmd.png doublecmd-qt.png
    mv doublecmd.sh doublecmd-qt.sh
build      : |
    cd doublecmd-${version}
    ./build.sh beta gtk2

    cd ../doublecmd-qt-${version}
    ./build.sh beta qt5
install    : |
    cd doublecmd-${version}
    ./install/linux/install.sh --install-prefix="$installdir"

    cd ../doublecmd-qt-${version}
    mv doublecmd doublecmd-qt
    mv doublecmd.zdli doublecmd-qt.zdli
    ./install/linux/install.sh --install-prefix="$installdir"

    rm -r $installdir/usr/share/*/doc
